### ISSUE TITLE
Application not starting on P40

### ISSUE THREAD

**Issue by vickiegpt** [SJTU-IPADS/PhoenixOS#24]
client:
```bash
root@mnfe-pve:~/examples/llama2-13b-chat-hf# env $phos python3 ./train.py
process id: 53641
loading model and tokenizer...
Loading checkpoint shards: 100%|_____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________| 3/3 [00:20<00:00,  6.70s/it]
[2025-05-05T03:57:13Z ERROR client::hijack::cudart_hijack] cudaGetDeviceCount returned error: cudaErrorProfilerNotInitialized
       0: std::thread::local::LocalKey<T>::with
       1: cudaGetDeviceCount
       2: _ZN3c104cuda28device_count_ensure_non_zeroEv
       3: _ZNK2at4cuda6detail9CUDAHooks8initCUDAEv
       4: _ZL24THCPModule_initExtensionP7_objectS0_
       5: cfunction_vectorcall_NOARGS
                 at /usr/local/src/conda/python-3.8.20/Objects/methodobject.c:463:24
       6: _PyObject_Vectorcall
                 at /usr/local/src/conda/python-3.8.20/Include/cpython/abstract.h:127:11
       7: call_function
                 at /usr/local/src/conda/python-3.8.20/Python/ceval.c:4963:13
       8: _PyEval_EvalFrameDefault
                 at /usr/local/src/conda/python-3.8.20/Python/ceval.c:3469:23
       9: PyEval_EvalFrameEx
                 at /usr/local/src/conda/python-3.8.20/Python/ceval.c:741:12
      10: function_code_fastcall
                 at /usr/local/src/conda/python-3.8.20/Objects/call.c:284:14
      11: _PyFunction_Vectorcall
                 at /usr/local/src/conda/python-3.8.20/Objects/call.c:411:20
      12: _PyObject_Vectorcall
                 at /usr/local/src/conda/python-3.8.20/Include/cpython/abstract.h:127:11
      13: PyObject_CallMethod
                 at /usr/local/src/conda/python-3.8.20/Objects/call.c:1030:14
      14: _ZN5torch5utils14cuda_lazy_initEv
      15: _ZN5torch8autogradL16THPVariable_cudaEP7_objectS2_S2_
      16: method_vectorcall_VARARGS_KEYWORDS
                 at /usr/local/src/conda/python-3.8.20/Objects/descrobject.c:332:14
      17: _PyObject_Vectorcall
                 at /usr/local/src/conda/python-3.8.20/Include/cpython/abstract.h:127:11
      18: call_function
                 at /usr/local/src/conda/python-3.8.20/Python/ceval.c:4963:13
```

server:
```bash
root@mnfe-pve:~/scripts/build_scripts# pos_cli --start --target daemon
 POS Log  >>>>>>>>>> PhOS Workspace <<<<<<<<<<
 _____  _                      _       ____   _____
|  __ \| |                    (_)     / __ \ / ____|
| |__) | |__   ___   ___ _ __  ___  _| |  | | (___
|  ___/| '_ \ / _ \ / _ \ '_ \| \ \/ / |  | |\___ \
| |    | | | | (_) |  __/ | | | |>  <| |__| |____) |
|_|    |_| |_|\___/ \___|_| |_|_/_/\_\\____/|_____/

 POS Log  PhoenixOS workspace created, welcome!
 POS Log  [POSParser @ 0x7d4288001100]  parser started
 POS Log  [POSWorker @ 0x7d4288001ea0]  worker started
 POS Log  parsing cached kernel metas from file /var/log/phos/daemon/llama2-13b-chat-hf_kernel_metas.txt...
 POS Log  reserved virtual memory space: device_id(0), base(0x7facd0000000), size(21340618752)
 POS Warn  [POSWorkspace_CUDA @ 0x7d44984e6580]  no api metadata was recorded in the api manager: api_id(121)
file:       ../pos/src/workspace.cpp;
function:   int POSWorkspace::pos_process(uint64_t, pos_client_uuid_t, std::vector<POSAPIParamDesp>, void*, uint64_t);
line:       404;
[2025-05-05T03:57:13Z ERROR server::dispatcher::cudart_exe] cudaGetDeviceCount returned error: cudaErrorProfilerNotInitialized
 POS Warn  [POSWorkspace_CUDA @ 0x7d44984e6580]  no api metadata was recorded in the api manager: api_id(152)
file:       ../pos/src/workspace.cpp;
function:   int POSWorkspace::pos_process(uint64_t, pos_client_uuid_t, std::vector<POSAPIParamDesp>, void*, uint64_t);
line:       404;
[2025-05-05T03:57:13Z ERROR server::dispatcher::cudart_exe] cudaGetLastError returned error: cudaErrorProfilerNotInitialized
 POS Warn  [POSWorkspace_CUDA @ 0x7d44984e6580]  no api metadata was recorded in the api manager: api_id(151)
file:       ../pos/src/workspace.cpp;
function:   int POSWorkspace::pos_process(uint64_t, pos_client_uuid_t, std::vector<POSAPIParamDesp>, void*, uint64_t);
line:       404;
Segmentation fault (core dumped)
 POS Warn  failed execution of command xpu-server 2>&1: exit_code(139)
 POS Warn  phosd start failed
 POS Error  CLI executed failed
```

Any idea?

**Comment by 913887524gsd** [comment]
I remember you should use inference.py rather than train.py.
The document does not say they support training llama XD.

**Comment by vickiegpt** [comment]
It happens on every cuda executables on my machine.

**Comment by vickiegpt** [comment]
fixed by recompiling the program, but now `pos_cli --dump` stuck at the recvfrom.
